name: flutter_push_client
description: Flutter client library for ReactPush update system. Allows Flutter apps to check for and download remote bundle updates.
version: 1.0.0
homepage: https://github.com/reactpush/react-push

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  archive: ^3.4.9
  crypto: ^3.0.3
  uuid: ^4.2.1
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  pointycastle: ^3.7.3
  asn1lib: ^1.5.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

